"""
pages/nrfi_tab.py
=================
NRFI / YRFI Predictions tab.

Reads outputs/nrfi_today.csv (generated by nrfi_today.py which uses the
trained ML model from models/nrfi_model.pkl).  Falls back to the legacy
heuristic nrfi.py if the ML output file doesn't exist yet.
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st


# ── helpers ───────────────────────────────────────────────────────────────────

def _safe_pct(val, default="—"):
    try:
        f = float(val)
        if math.isnan(f):
            return default
        return f"{f * 100:.1f}%"
    except Exception:
        return default


def _prob_bar_html(prob: float, green: bool) -> str:
    pct = max(0.0, min(1.0, prob)) * 100
    color = "#00c853" if green else "#e53935"
    track = "rgba(255,255,255,0.08)"
    return (
        f'<div style="display:flex;align-items:center;gap:0.5rem;">'
        f'<div style="width:80px;background:{track};border-radius:3px;height:5px;flex-shrink:0;">'
        f'<div style="width:{pct:.0f}%;background:{color};height:5px;border-radius:3px;"></div></div>'
        f'<span style="font-family:\'IBM Plex Mono\',monospace;font-size:0.7rem;color:#a0b0c4;">'
        f'{pct:.0f}%</span></div>'
    )


# ── ML-model based rendering ──────────────────────────────────────────────────

def _render_ml(df: pd.DataFrame):
    """Render the ML model NRFI output (nrfi_today.csv)."""
    st.markdown(
        '<div style="color:#6a7d94;font-size:0.78rem;margin-bottom:1rem;">'
        f'{len(df)} games · ML model predictions</div>',
        unsafe_allow_html=True,
    )

    # Column header
    col_defs = [1.6, 2.2, 2.2, 0.9, 1.4, 1.4]
    labels   = ["Matchup", "Away SP", "Home SP", "Pick", "NRFI %", "YRFI %"]
    hdr_cols = st.columns(col_defs)
    for col, lbl in zip(hdr_cols, labels):
        col.markdown(
            f'<div style="font-family:\'IBM Plex Mono\',monospace;font-size:0.6rem;'
            f'color:#6a7d94;text-transform:uppercase;letter-spacing:0.08em;'
            f'padding-bottom:0.3rem;border-bottom:1px solid rgba(255,255,255,0.06);">'
            f'{lbl}</div>',
            unsafe_allow_html=True,
        )

    for _, row in df.iterrows():
        is_nrfi    = str(row.get("pick", "")).upper() == "NRFI"
        pick_color = "#00c853" if is_nrfi else "#e53935"
        pick_bg    = "rgba(0,200,83,0.1)" if is_nrfi else "rgba(229,57,53,0.1)"
        pick_label = "NRFI" if is_nrfi else "YRFI"

        away = str(row.get("away_team", "—"))
        home = str(row.get("home_team", "—"))
        away_sp = str(row.get("away_sp", "TBD"))
        home_sp = str(row.get("home_sp", "TBD"))

        nrfi_prob = row.get("nrfi_prob")
        yrfi_prob = row.get("yrfi_prob")

        row_cols = st.columns(col_defs)

        row_cols[0].markdown(
            f'<div style="font-family:\'Barlow Condensed\',sans-serif;font-size:1rem;'
            f'font-weight:700;color:#f0f2f5;padding:0.4rem 0;">{away} @ {home}</div>',
            unsafe_allow_html=True,
        )
        row_cols[1].markdown(
            f'<div style="font-size:0.78rem;color:#a0b0c4;padding:0.4rem 0;">{away_sp}</div>',
            unsafe_allow_html=True,
        )
        row_cols[2].markdown(
            f'<div style="font-size:0.78rem;color:#a0b0c4;padding:0.4rem 0;">{home_sp}</div>',
            unsafe_allow_html=True,
        )
        row_cols[3].markdown(
            f'<div style="padding:0.4rem 0;">'
            f'<span style="background:{pick_bg};border:1px solid {pick_color}33;'
            f'color:{pick_color};font-family:\'IBM Plex Mono\',monospace;font-size:0.62rem;'
            f'font-weight:700;letter-spacing:0.06em;padding:0.2rem 0.45rem;border-radius:4px;">'
            f'{pick_label}</span></div>',
            unsafe_allow_html=True,
        )

        nrfi_bar = _prob_bar_html(float(nrfi_prob), green=True) if pd.notna(nrfi_prob) else "—"
        yrfi_bar = _prob_bar_html(float(yrfi_prob), green=False) if pd.notna(yrfi_prob) else "—"
        row_cols[4].markdown(f'<div style="padding:0.3rem 0;">{nrfi_bar}</div>', unsafe_allow_html=True)
        row_cols[5].markdown(f'<div style="padding:0.3rem 0;">{yrfi_bar}</div>', unsafe_allow_html=True)

        st.markdown(
            '<div style="height:1px;background:rgba(255,255,255,0.04);margin:0;"></div>',
            unsafe_allow_html=True,
        )


# ── heuristic fallback rendering ──────────────────────────────────────────────

def _render_heuristic():
    """Fall back to the legacy Poisson-heuristic nrfi.py when no ML output exists."""
    try:
        from nrfi import compute_nrfi_for_today
        rows = compute_nrfi_for_today()
    except Exception as e:
        st.warning(f"Could not load heuristic NRFI: {e}")
        return

    if not rows:
        st.markdown(
            '<div style="color:#6a7d94;padding:1rem 0;font-size:0.9rem;">'
            'No games found for today (heuristic mode).</div>',
            unsafe_allow_html=True,
        )
        return

    st.markdown(
        '<div style="color:#6a7d94;font-size:0.78rem;margin-bottom:1rem;">'
        f'{len(rows)} games · heuristic model (Poisson λ)</div>',
        unsafe_allow_html=True,
    )

    col_defs = [1.4, 2.0, 2.0, 1.0, 1.3, 1.3, 1.3]
    labels   = ["Matchup", "Pitcher A", "Pitcher B", "Lean", "P(NRFI)", "λ A", "λ B"]
    hdr_cols = st.columns(col_defs)
    for col, lbl in zip(hdr_cols, labels):
        col.markdown(
            f'<div style="font-family:\'IBM Plex Mono\',monospace;font-size:0.6rem;'
            f'color:#6a7d94;text-transform:uppercase;letter-spacing:0.08em;'
            f'padding-bottom:0.3rem;border-bottom:1px solid rgba(255,255,255,0.06);">'
            f'{lbl}</div>',
            unsafe_allow_html=True,
        )

    for g in rows:
        lean = g.get("lean", "PASS")
        lean_color = {"YES": "#00c853", "NO": "#e53935", "PASS": "#7a8a9e"}.get(lean, "#7a8a9e")
        lean_bg    = {"YES": "rgba(0,200,83,0.1)", "NO": "rgba(229,57,53,0.1)", "PASS": "rgba(255,255,255,0.04)"}.get(lean, "rgba(255,255,255,0.04)")

        sa = g.get("side_a", {})
        sb = g.get("side_b", {})

        row_cols = st.columns(col_defs)
        row_cols[0].markdown(
            f'<div style="font-family:\'Barlow Condensed\',sans-serif;font-size:1rem;'
            f'font-weight:700;color:#f0f2f5;padding:0.4rem 0;">'
            f'{g["team_a"]} vs {g["team_b"]}</div>',
            unsafe_allow_html=True,
        )
        row_cols[1].markdown(f'<div style="font-size:0.78rem;color:#a0b0c4;padding:0.4rem 0;">{sa.get("pitcher_name","—")}</div>', unsafe_allow_html=True)
        row_cols[2].markdown(f'<div style="font-size:0.78rem;color:#a0b0c4;padding:0.4rem 0;">{sb.get("pitcher_name","—")}</div>', unsafe_allow_html=True)
        row_cols[3].markdown(
            f'<div style="padding:0.4rem 0;">'
            f'<span style="background:{lean_bg};color:{lean_color};'
            f'font-family:\'IBM Plex Mono\',monospace;font-size:0.62rem;font-weight:700;'
            f'letter-spacing:0.06em;padding:0.2rem 0.45rem;border-radius:4px;">{lean}</span></div>',
            unsafe_allow_html=True,
        )
        p_nrfi = g.get("p_nrfi")
        nrfi_bar = _prob_bar_html(float(p_nrfi), green=True) if p_nrfi is not None else "—"
        row_cols[4].markdown(f'<div style="padding:0.3rem 0;">{nrfi_bar}</div>', unsafe_allow_html=True)

        la = sa.get("runs_lambda")
        lb = sb.get("runs_lambda")
        row_cols[5].markdown(f'<div style="font-family:\'IBM Plex Mono\',monospace;font-size:0.7rem;color:#a0b0c4;padding:0.4rem 0;">{f"{la:.2f}" if la is not None else "—"}</div>', unsafe_allow_html=True)
        row_cols[6].markdown(f'<div style="font-family:\'IBM Plex Mono\',monospace;font-size:0.7rem;color:#a0b0c4;padding:0.4rem 0;">{f"{lb:.2f}" if lb is not None else "—"}</div>', unsafe_allow_html=True)

        st.markdown('<div style="height:1px;background:rgba(255,255,255,0.04);margin:0;"></div>', unsafe_allow_html=True)


# ── public render function ────────────────────────────────────────────────────

def render(base_dir: Path):
    """
    Main entry point called from app.py.
    base_dir: the root of the MLB Betting Website folder.
    """
    ml_output = base_dir / "outputs" / "nrfi_today.csv"

    # ── Run / refresh button ──────────────────────────────────────────────────
    with st.expander("🔄 Generate NRFI predictions", expanded=not ml_output.exists()):
        st.markdown(
            '<div style="color:#6a7d94;font-size:0.82rem;margin-bottom:1rem;">'
            'Requires <code>models/nrfi_model.pkl</code>. '
            'Run <code>python nrfi_train.py</code> first if you haven\'t trained the model yet.</div>',
            unsafe_allow_html=True,
        )
        if st.button("Generate NRFI Predictions Now", key="nrfi_run_btn"):
            try:
                import sys
                sys.path.insert(0, str(base_dir))
                from nrfi_today import run_nrfi
                with st.spinner("Fetching schedule and running NRFI model…"):
                    run_nrfi()
                st.success("✅ NRFI predictions saved.")
                st.cache_data.clear()
                st.rerun()
            except Exception as e:
                st.error(f"NRFI error: {e}")

    # ── Load and display ──────────────────────────────────────────────────────
    if ml_output.exists():
        try:
            df = pd.read_csv(ml_output, low_memory=False)
            for col in ["nrfi_prob", "yrfi_prob", "threshold"]:
                if col in df.columns:
                    df[col] = pd.to_numeric(df[col], errors="coerce")
            if not df.empty:
                df = df.sort_values("nrfi_prob", ascending=False)
                _render_ml(df)
                return
        except Exception as e:
            st.warning(f"Could not read nrfi_today.csv ({e}). Falling back to heuristic model.")

    # Fallback
    st.markdown(
        '<div style="color:#6a7d94;font-size:0.82rem;margin-bottom:1rem;">'
        '<em>ML model output not found — showing heuristic Poisson model.</em></div>',
        unsafe_allow_html=True,
    )
    _render_heuristic()
